# Generated by Django 4.2.30 on 2026-06-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0003_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
